[PART-73] Avaliação automatizada de propostas
sep-es-br/participe-web pull request #231
Opened 2024-06-12 20:43 UTC by AUFaria

Como usuário Avaliador do Participe, desejo realizar o preenchimento da avaliação das propostas diretamente no sistema, para que possamos automatizar essas informações.

2024-06-12 21:06 UTC, wbcrux commented on src/app/core/menu/app.menu.component.ts
> -    if (person.roles.includes('Administrator')) {
Verificar a remoção da condicional do Administrador.

2024-06-12 21:06 UTC, wbcrux commented on src/app/core/menu/submenu/app.submenu.component.html
> +    <a *ngIf="!child.routerLink" style="padding-bottom: 0.45rem; padding-top: 0.25rem;" (mouseenter)="onMouseEnter(i)">
Remover style inline

2024-06-12 21:21 UTC, wbcrux commented on src/app/modules/proposal-evaluation/proposal-evaluation.component.ts
> +        this.localityOptions.unshift({ label: "Todos", value: null });
Inserir Internacionalização do Label

2024-06-12 21:21 UTC, wbcrux commented on src/app/modules/proposal-evaluation/proposal-evaluation.component.ts
> +        this.planItemOptions.unshift({ label: "Todos", value: null });
Inserir Internacionalização do Label

2024-06-12 21:23 UTC, wbcrux commented on src/app/shared/services/proposal-evaluation.service.ts
Inserir internacionalização dos textos

2024-06-12 21:27 UTC, AUFaria commented on src/app/core/menu/app.menu.component.ts
> -    if (person.roles.includes('Administrator')) {
Remoção de verificação de papel do usuário redundante

2024-06-12 22:07 UTC, AUFaria commented on src/app/shared/services/proposal-evaluation.service.ts
Ajustado em https://github.com/sep-es-br/participe-web/pull/231/commits/3890a57b299ad1db5bde74161b6dc17a09d6e914

2024-06-12 22:07 UTC, AUFaria commented on src/app/modules/proposal-evaluation/proposal-evaluation.component.ts
> +        this.planItemAreaOptions.unshift({ label: "Todos", value: null });
Ajustado em https://github.com/sep-es-br/participe-web/pull/231/commits/3890a57b299ad1db5bde74161b6dc17a09d6e914

2024-06-12 22:07 UTC, AUFaria commented on src/app/modules/proposal-evaluation/proposal-evaluation.component.ts
> +        this.planItemOptions.unshift({ label: "Todos", value: null });
Ajustado em https://github.com/sep-es-br/participe-web/pull/231/commits/3890a57b299ad1db5bde74161b6dc17a09d6e914

2024-06-12 22:07 UTC, AUFaria commented on src/app/modules/proposal-evaluation/proposal-evaluation.component.ts
> +        this.localityOptions.unshift({ label: "Todos", value: null });
Ajustado em https://github.com/sep-es-br/participe-web/pull/231/commits/3890a57b299ad1db5bde74161b6dc17a09d6e914

2024-06-12 22:07 UTC, AUFaria commented on src/app/modules/proposal-evaluation/evaluate/evaluate.component.ts
> +    return this.proposalEvaluationForm.get("budgetPlan").value ?? 'Nenhum plano orçamentário fornecido';
Ajustado em https://github.com/sep-es-br/participe-web/pull/231/commits/3890a57b299ad1db5bde74161b6dc17a09d6e914

2024-06-12 22:07 UTC, AUFaria commented on src/app/core/menu/submenu/app.submenu.component.html
> +    <a *ngIf="!child.routerLink" style="padding-bottom: 0.45rem; padding-top: 0.25rem;" (mouseenter)="onMouseEnter(i)">
Ajustado em https://github.com/sep-es-br/participe-web/pull/231/commits/3890a57b299ad1db5bde74161b6dc17a09d6e914

2024-06-13 16:52 UTC, wbcrux requested changes

2024-06-13 16:52 UTC, wbcrux commented on src/app/shared/services/proposal-evaluation.service.ts
> +  private reasonOptions: Array<string> = [
Inserir internacionalização

2024-06-13 17:07 UTC, wbcrux approved these changes

2024-06-13 17:07 UTC, merged